### PR TITLE
Issue #247 - Replace `execute` with `backend.run()` in `qiskit-qec`

### PR DESCRIPTION
**Pull request by robotAstray**
### Summary:

This pull request aims to resolve issue #247 by replacing the outdated `execute` function with the more up-to-date `backend.run` method in the `qiskit-qec` codebase. 

### Details and comments:

- Replaced the usage of `execute` with `backend.run` for simulating the quantum circuit.

### Additional Notes:

The following files have been modified:

- `test/matching/test_circuitmatcher.py`
- `test/matching/test_repetitionmatcher.py`
- `src/qiskit_qec/analysis/faultsampler.py`
- `src/qiskit_qec/analysis/faultenumerator.py`
- `test/heavy_hex_codes/test_heavy_hex_decoder.py`

### CODE REVIEW

**Comment by robotAstray** [comment]
@IceKhan13 PR 381 is now ready for review

**Comment by robotAstray** [comment]
@grace-harper I have fixed #247 and it is ready for review

**Comment by robotAstray** [comment]
Hello @grace-harper , I will look into the issues. Thank you

**Comment by robotAstray** [comment]
Hello @grace-harper the test errors are related to a bug I identified and described in issue #380. I do not think is related to the work I did on  issue #247. Regarding the lint/style check. I will fix those. Thank you.

**Review by grace-harper — APPROVED** [review]
LGTM

**Pull request merged**
