### PR TITLE
Update python version to 3.8-3.11

### PR DESCRIPTION
**Pull request by arnaucasau**
### Summary

Update of the python version to work with python 3.8 to 3.11.

### CODE REVIEW

**Review by grace-harper — APPROVED** [review]
LGTM

**Review by grace-harper — CHANGES_REQUESTED** [review]
- [ ] Can you update python versions for black the `pyproject.toml`? Currently, `target-version = ['py36', 'py37', 'py38', 'py39']` includes python 3.6 and 3.7 


- [ ]  Can you update python versions in the `.github/workflows/pypi-release.yml`? ` python-version: '3.7'` still has it's own section.

- [ ] Can you update python versions in  `.github/workflows/tests.yml`  python 3.7 is still in `python-version: [3.7, 3.9]` 

- [ ]

**Comment by arnaucasau** [comment]
Thank you Grace, updated the `pyproject.toml` to python 3.8-3.11. I think `.github/workflows/pypi-release.yml` and `.github/workflows/tests.yml ` are already updated, but maybe I'm wrong.

**Comment by Eric-Arellano** [comment]
The GitHub branch protection rules will need to be updated by you @grace-harper to stop looking for 3.7 and 3.9 when merging. Instead, it should look for 3.8 and 3.11, but that probably won't pop up in the list until this is merged.

**Comment by grace-harper** [comment]
> The GitHub branch protection rules will need to be updated by you @grace-harper to stop looking for 3.7 and 3.9 when merging. Instead, it should look for 3.8 and 3.11, but that probably won't pop up in the list until this is merged.

Hey @Eric-Arellano  Thanks. I went ahead and removed the need for 3.7. We want it to look for 3.8-3.11, right?

**Comment by Eric-Arellano** [comment]
> We want it to look for 3.8-3.11, right?

Only 3.8 and 3.11. While it's technically more correct to run CI for 3.9 and 3.10 too, it's an extremely high chance that your code will work with 3.9 and 3.10 if it already works for 3.8 and 3.11. It's not worth wasting the compute resources to also test 3.9 and 3.10, which takes up CI resources and has an environmental cost.

**Review by grace-harper — APPROVED** [review]
LGTM

**Pull request merged**
